before_commands:
    - "composer install --dev --prefer-source"

tools:
    php_code_coverage:
        enabled: true
        test_command: phpunit -c phpunit.xml.dist
        filter:
            paths: ["lib/*"]
    php_code_sniffer:
        enabled: true
        config:
            standard: PSR2
        filter:
            paths: ["lib/*"]
    php_cpd:
        enabled: true
        excluded_dirs: ["examples", "tests", "docs", "vendor"]
    php_cs_fixer:
        enabled: true
        config:
            level: all
        filter:
            paths: ["lib/*", "tests/UserApp/*"]
    php_loc:
        enabled: true
    php_mess_detector:
        enabled: true
        filter:
            paths: ["lib/*"]
    php_pdepend:
        enabled: true
        excluded_dirs: ["tests", "examples", "docs", "vendor"]
    php_analyzer: true
    php_analyzer:
        filter:
            paths: ["lib/*", "tests/UserApp/*"]
    sensiolabs_security_checker: true